db:
  image: postgres:9.6
  ports:
    - 5432:5432
  environment: &db_environment
    POSTGRES_DB: work-journal
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: shievoh5Nohg2Ohd
  volumes:
    - "./src/db/:/docker-entrypoint-initdb.d"

api:
  build: .
  ports:
    - 3000:3000
  links:
    - db:db
  environment:
    <<: *db_environment
    POSTGRES_HOST: db
